#!/bin/python3

import os
import sys

# Complete the solve function below.
def solve(x):
    m=1
    sc=0
    while sc<=x:
        l=0
        sc+=(m*m)
        l+=(sc+((m+1)*(m+1)))
        if l<=x:
            m+=1
        else:
            break
    return m

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        x = int(input())

        result = solve(x)

        fptr.write(str(result) + '\n')

    fptr.close()
